/** The 32 teams, keyed by the abbreviations nflverse uses. `color` is the primary team colour. */
export const TEAMS: Record<string, { name: string; nick: string; color: string }> = {
  ARI: { name: "Arizona", nick: "Cardinals", color: "#97233F" },
  ATL: { name: "Atlanta", nick: "Falcons", color: "#A71930" },
  BAL: { name: "Baltimore", nick: "Ravens", color: "#241773" },
  BUF: { name: "Buffalo", nick: "Bills", color: "#00338D" },
  CAR: { name: "Carolina", nick: "Panthers", color: "#0085CA" },
  CHI: { name: "Chicago", nick: "Bears", color: "#0B162A" },
  CIN: { name: "Cincinnati", nick: "Bengals", color: "#FB4F14" },
  CLE: { name: "Cleveland", nick: "Browns", color: "#311D00" },
  DAL: { name: "Dallas", nick: "Cowboys", color: "#003594" },
  DEN: { name: "Denver", nick: "Broncos", color: "#FB4F14" },
  DET: { name: "Detroit", nick: "Lions", color: "#0076B6" },
  GB: { name: "Green Bay", nick: "Packers", color: "#203731" },
  HOU: { name: "Houston", nick: "Texans", color: "#03202F" },
  IND: { name: "Indianapolis", nick: "Colts", color: "#002C5F" },
  JAX: { name: "Jacksonville", nick: "Jaguars", color: "#006778" },
  KC: { name: "Kansas City", nick: "Chiefs", color: "#E31837" },
  LA: { name: "LA Rams", nick: "Rams", color: "#003594" },
  LAC: { name: "LA Chargers", nick: "Chargers", color: "#0080C6" },
  LV: { name: "Las Vegas", nick: "Raiders", color: "#000000" },
  MIA: { name: "Miami", nick: "Dolphins", color: "#008E97" },
  MIN: { name: "Minnesota", nick: "Vikings", color: "#4F2683" },
  NE: { name: "New England", nick: "Patriots", color: "#002244" },
  NO: { name: "New Orleans", nick: "Saints", color: "#D3BC8D" },
  NYG: { name: "NY Giants", nick: "Giants", color: "#0B2265" },
  NYJ: { name: "NY Jets", nick: "Jets", color: "#125740" },
  PHI: { name: "Philadelphia", nick: "Eagles", color: "#004C54" },
  PIT: { name: "Pittsburgh", nick: "Steelers", color: "#FFB612" },
  SEA: { name: "Seattle", nick: "Seahawks", color: "#002244" },
  SF: { name: "San Francisco", nick: "49ers", color: "#AA0000" },
  TB: { name: "Tampa Bay", nick: "Buccaneers", color: "#D50A0A" },
  TEN: { name: "Tennessee", nick: "Titans", color: "#4B92DB" },
  WAS: { name: "Washington", nick: "Commanders", color: "#5A1414" },
};

export const TEAM_CODES = Object.keys(TEAMS);
